title: Welcome to Time Delay Lens Modeling Challenge!
description: Testing accuracy on lens modeling and inference of cosmological parameters --- blind.
show_downloads: false
theme: jekyll-theme-cayman
